Repository supershy42/game, pull requests merged in 2024-12, with the labels that each got.

#8 CreateGameRoom API 구현
  config/urls.py
  game/migrations/0001_initial.py
  game/models.py
  game/serializers.py
  game/tests.py
  game/urls.py
  game/views.py
Labels: feature

#11 Reception Management 및 CustomMiddleware 구현
  config/middlewares.py
  config/routing.py
  config/services.py
  config/settings.py
  game/consumers.py
  game/migrations/0001_initial.py
  game/models.py
  game/redis_utils.py
  game/routing.py
  game/serializers.py
  game/services.py
  game/tests.py
  game/urls.py
  game/views.py
  requirements.txt
Labels: feature

#12 CORS 설정 및 config/middlewares 이름 변경
  config/middleware.py
  config/routing.py
  config/settings.py
  requirements.txt
Labels: feature

#17 ReceptionListView API 구현
  config/settings.py
  game/tests.py
  game/urls.py
  game/views.py
Labels: feature

#19 Reception 초대 구현
  config/close_codes.py
  config/error_type.py
  config/middleware.py
  config/response_builder.py
  config/services.py
  config/settings.py
  reception/consumers.py
  reception/redis_utils.py
  reception/serializers.py
  reception/services.py
  reception/tests/__init__.py
  reception/tests/test_invite_join.py
  reception/tests/tests.py
  reception/views.py
Labels: feature

#20 Reception to arena
  arena/__init__.py
  arena/admin.py
  arena/apps.py
  arena/consumers.py
  arena/migrations/__init__.py
  arena/models.py
  arena/routing.py
  arena/services.py
  arena/tests.py
  arena/views.py
  config/close_codes.py
  config/routing.py
  config/settings.py
  reception/consumers.py
  reception/redis_utils.py
  reception/services.py
  reception/views.py
Labels: feature

#21 Arena Prototype 구현
  arena/consumers.py
  arena/domain/__init__.py
  arena/domain/arena.py
  arena/domain/arena_manager.py
  arena/domain/ball.py
  arena/domain/bar.py
  arena/domain/player.py
  arena/enums.py
  config/settings.py
  reception/consumers.py
Labels: feature

#23 Reception delete and access bug 수정
  reception/consumers.py
  reception/redis_utils.py
Labels: bug

#24 Arena 종료에 대한 모든 것
  arena/consumers.py
  arena/domain/arena.py
  config/consumer_utils.py
  reception/services.py
Labels: feature

#25 is_blacklisted 함수 호출에 await 추가
  reception/services.py
Labels: bug

#32 Tournament prototype 구현
  arena/consumers.py
  config/redis_utils.py
  config/services.py
  config/settings.py
  reception/consumers.py
  reception/serializers.py
  reception/services.py
  reception/tests/test_invite_join.py
  reception/views.py
  requirements.txt
  tournament/__init__.py
  tournament/admin.py
  tournament/apps.py
  tournament/migrations/0001_initial.py
  tournament/migrations/__init__.py
  tournament/models.py
  tournament/tests.py
  tournament/views.py
Labels: feature

#33 Tournament create API 구현
  config/error_type.py
  config/urls.py
  tournament/models.py
  tournament/serializers.py
  tournament/services.py
  tournament/urls.py
  tournament/views.py
Labels: feature

#35 Tournament start API 구현
  config/error_type.py
  config/services.py
  tournament/models.py
  tournament/serializers.py
  tournament/services.py
  tournament/urls.py
  tournament/views.py
Labels: feature

#36 Tournament fix
  arena/migrations/0001_initial.py
  arena/models.py
  arena/serializers.py
  config/services.py
  tournament/migrations/0002_alter_tournament_name_tournamentmatch_delete_match.py
  tournament/models.py
  tournament/serializers.py
  tournament/services.py
  tournament/urls.py
  tournament/views.py
Labels: feature

#37 Improve Dockerfile Configuration and Add Health Check Functionality
  Dockerfile
  utils/entrypoint.sh
Labels: feature

#41 Websocket 연결 시 토큰 전달 방식 변경
  config/middleware.py
Labels: feature

#38 Tournament bracket API 구현
  arena/serializers.py
  tournament/migrations/0003_remove_tournamentmatch_tournament_and_more.py
  tournament/migrations/0004_tournamentmatch_parent_match_and_more.py
  tournament/models.py
  tournament/serializers.py
  tournament/services.py
  tournament/urls.py
  tournament/views.py
Labels: feature

#43 Env 설정
  config/redis_utils.py
  config/settings.py
Labels: feature

#39 Tournament 진행 로직 구현
  arena/consumers.py
  arena/domain/arena.py
  arena/domain/ball.py
  arena/domain/bar.py
  arena/domain/player.py
  arena/enums.py
  arena/migrations/0002_alter_normalmatch_state.py
  arena/models.py
  arena/routing.py
  arena/services.py
  config/close_codes.py
  tournament/migrations/0005_rename_parent_match_player_slot_tournamentmatch_parent_match_player_team_and_more.py
  tournament/models.py
  tournament/serializers.py
  tournament/services.py
Labels: feature

#40 Match history API 구현
  arena/consumers.py
  arena/domain/arena.py
  arena/domain/arena_manager.py
  arena/migrations/0003_rename_left_score_normalmatch_left_player_score_and_more.py
  arena/migrations/0004_normalmatch_unique_id.py
  arena/models.py
  arena/serializers.py
  arena/services.py
  arena/urls.py
  arena/views.py
  config/urls.py
  reception/consumers.py
  reception/services.py
  tournament/migrations/0006_rename_left_score_tournamentmatch_left_player_score_and_more.py
  tournament/migrations/0007_tournamentmatch_unique_id.py
  tournament/services.py
Labels: feature

#46 Migrate server initiation to Daphne ASGI server
  Dockerfile
Labels: feature

#42 Reception access 방식 변경
  arena/consumers.py
  arena/services.py
  config/error_type.py
  config/redis_services.py
  config/redis_utils.py
  config/services.py
  reception/consumers.py
  reception/jwt_utils.py
  reception/migrations/0003_reception_creator.py
  reception/models.py
  reception/serializers.py
  reception/services.py
  reception/tests/test_invite_join.py
  reception/views.py
Labels: feature

#44 Participants 메시지 형식 수정 & toggle ready로 변경 & 자잘한 버그 수정
  config/redis_services.py
  config/settings.py
  reception/consumers.py
  reception/services.py
Labels: bug, feature

#45 User detail in response
  arena/dto.py
  arena/serializers.py
  arena/views.py
  config/redis_services.py
  config/settings.py
  reception/services.py
  requirements.txt
  tournament/dto.py
  tournament/serializers.py
  tournament/views.py
Labels: feature

#50 Python 버전 수정 및 PostgreSQL 클라이언트 설치, API Gateway 요청 제한 설정
  Dockerfile
  config/settings.py
  requirements.txt
Labels: feature, refactoring
